spring:
  redis:
    database: 1
    host: 10.240.1.13
    port: 6380
    password: root
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 100ms
        min-idle: 0