spring:
  datasource:
      url: jdbc:mysql://localhost:3306/loandemo?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  redis:
    database: 1
    host: 10.240.1.13
    port: 6379
    password: root
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        max-wait: 100ms
        min-idle: 0
isProduct: false